# Generated by Django 2.2.24 on 2021-09-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour_package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_id', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('start_dest', models.CharField(max_length=20)),
                ('tour_duration', models.CharField(max_length=10)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
