# Generated by Django 3.2.7 on 2021-10-30 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='guests',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
