# Generated by Django 3.2.7 on 2021-10-07 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_auto_20210914_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartDest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_dest', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='tour_package',
            name='image',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='tour_package',
            name='start_dest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.startdest'),
        ),
    ]
