# Generated by Django 3.2.7 on 2021-10-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0003_auto_20211007_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour_package',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
